library(tidyverse)
library(prophet)
tags <- c("Tur","Tar","Cog","Fel","Din","Mat","Geo","Fiz","Kim","Bio","Tot")

# time series with nets
source("cleaner.R")

clean("a")

to_analyze <- a %>% 
  select(DATE, Tot_Net) %>% 
  rename(ds = DATE, y= Tot_Net)

# TIME SERIES
time_series_model <- prophet(to_analyze)

future <- make_future_dataframe(time_series_model, periods = 30)

forecast <- predict(time_series_model, future)
summary(forecast)
plot(time_series_model, forecast)

prophet_plot_components(time_series_model, forecast)

changepoints <- as.data.frame(time_series_model$changepoints)

ggplot(to_analyze, aes(ds, y)) +
  geom_line() +
  geom_vline(xintercept = changepoints$ds, linetype = "dashed", color = "red")

time_series_model

# LINEAR REGRESSION

linear <- lm(y~ds, to_analyze)
summary(linear)

ggplot(to_analyze)+
  geom_histogram(mapping=aes(y), binwidth = 2)

# Scatterplot with Regression Line:
# Use: This plot shows the actual data points (scatterplot) along with the fitted regression line. It helps you visually assess the linear relationship between the independent and dependent variables. If the scatterplot shows a clear linear pattern, it suggests that the linear regression model may be appropriate for the data.

ggplot(data = to_analyze, aes(x = ds, y = y))+
  geom_point() +
  geom_smooth(formula = y ~ x, method = "lm", linetype = "dotted", color = "red") +
  guides(color = "none")

# Residual Plot:
# Use: A residual plot displays the differences between the observed values and the predicted values (residuals) on the y-axis and the independent variable on the x-axis. It helps you identify patterns, outliers, or heteroscedasticity in the residuals. A well-behaved residual plot should show no obvious patterns and residuals should be randomly scattered around zero.

residuals <- resid(lm(y ~ ds, data = to_analyze))
plot(to_analyze$ds, residuals, main = "Residual Plot", xlab = "ds", ylab = "Residuals")
abline(h = 0, col = "red")

#Histogram of Residuals:
# Use: A histogram of residuals provides a visual representation of the distribution of the model's errors. It helps you assess whether the residuals are approximately normally distributed. A normal distribution of residuals is a common assumption of linear regression.
hist(residuals, main = "Histogram of Residuals", xlab = "Residuals", ylab = "Frequency")

# Q-Q Plot (Quantile-Quantile Plot):
# Use: A Q-Q plot compares the distribution of residuals to a theoretical normal distribution. It's a useful tool to check if the residuals follow a normal distribution. In a Q-Q plot, residuals should closely follow a diagonal line if they are normally distributed. Departures from the line can indicate non-normality.

qqnorm(residuals)
qqline(residuals)

# Fitted vs. Residuals Plot:
# Use: This plot assesses the relationship between the predicted (fitted) values and the residuals. It helps you identify patterns or heteroscedasticity in the residuals. If the spread of residuals varies systematically with the fitted values, it can suggest a violation of model assumptions.

plot(fitted(lm(y ~ ds, data = to_analyze)), residuals, main = "Fitted vs. Residuals Plot", xlab = "Fitted Values", ylab = "Residuals")
abline(h = 0, col = "red")

# Diagnostic Plots:
# Use: The diagnostic plots generated by the plot.lm function in R include a combination of the plots mentioned above, allowing you to quickly assess the model's assumptions and performance. These plots can be especially helpful for a comprehensive model evaluation.

model <- lm(y ~ ds, data = to_analyze)
plot(model)


t_test <- t.test(to_analyze$y, mu = 1)
t_test


